Custom DNS server

diff --git a/linux/bin/ss-tun b/linux/bin/ss-tun
--- a/linux/bin/ss-tun
+++ b/linux/bin/ss-tun
@@ -33,7 +33,7 @@ is_cmd_exist resolvconf
 # gateway
 gw="$(/sbin/ip route | awk '/default via/ { print $3 }')"
 tun_ip='11.11.11.11'
-dns_server='1.1.1.1'
+dns_server=$(cat /etc/ss-tun/dns.txt)
 
 # parse config.json of Shadowsocks
 ss_config=/etc/ss-tun/config.json
@@ -101,7 +101,7 @@ ip addr add "$tun_ip/32" dev tun114514 || {
 }
 
 # set DNS
-echo -n "nameserver $dns_server" | resolvconf -a tun114514
+echo -n "nameserver $dns_server" | resolvconf -a tun114514 || error "Failed to set DNS to '$dns_server'"
 
 # bypass LAN
 ip route add 10.0.0.0/8 via "$gw"
